version: '3.1'

services:
  db:
    image: nodejsdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodejs
      MYSQL_USER: nodejs
      MYSQL_PASSWORD: nodejs
    ports:
      - 3306:3306
